language: go
go:
- 1.10.x
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/carlescere/scheduler
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
- mkdir /tmp/backup
install:
- go get golang.org/x/text/encoding
- go get golang.org/x/net/context
- go get github.com/stretchr/testify/assert
os:
- linux
env:
  global: 
  matrix:
  - GIT_BACKUP_DIR=/tmp/backup
  - secure: jj9MhP+XX2gF67j+qTcb/4KsfSqOWKRDzRS/mqw4sNJfKtc1Ptft0Azx8H+WexN+ymoA6FYj39ypuK6CMHmgKuykSQC8Yl8qU+nDEiiO22OgVZfYivfh1vsjJTT0gtzq6h9zkz3cNUVpEnP1iZZ+Wl+xg0k+7MIQcoWz6y7j4GRtIbolli2clzasEpVWuNtM8GhmP1GZCsqwU43qmiK0zYyQZtTt4CMGZqlMjrSnJDM0+oKsG0tc+P/joKfaePYctBBk6UbXOrkQ2sgCvnPs1KrRxN2Gr1hSLCq1VfWA0G+JmKImPSl8qODl1+g6oBKN/b1z06Qr9UZAO3nw5J4AbbgpHapC/k/3NaRAralKiDZGy526zl5l8cZEouiiUFW4NM97mu1PmHN621bZeTzXH3m69dcHQoQnGk/6z9N6wJfoytKBZv8S4T44tfzzAFZh4/3o2nuJ8jpAUu1PVzY2UMc6ePfmgvFtD3OVzty+Njlqtckqkv3cfZ3rUpz8wg8NGAe0vfM56xyeL7JQmRg8wwJgpd5KqcmJgd/Zb+jjKuXuMYdWHe8fAWoZw0uNj28rdx7VrwQaEM1uhjnBp2DeGp8rX6taZIVUmqQ6Qwc8BEuQstyyiLt1j+uA71EZNYM2xdcoyiwwPLc5deb2QJKymZPUowqUUvBfGQIv7+eZXSM=
script:
- base=$(echo $PWD | sed "s|$GOPATH/src/||") && go test -race -v $(go list ./... |
  grep -v vendor | sed "s|$base/|./|")
- "$GOPATH/bin/goveralls -service=travis-ci"
