language: go
go:
- 1.10.x
- tip
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/carlescere/scheduler
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
- mkdir /tmp/backup
install:
- go get golang.org/x/text/encoding
- go get golang.org/x/net/context
- go get github.com/stretchr/testify/assert
os:
- linux
env:
  global:
    secure: oSL9vt6xrpwMQJSkh36tDNNAaeKpz/FBwyJHo6BbuoaJ46f8Mm0W84wyIJofECLNPXtWJuHqypYuXBv0RX49FeMtbo/2oaBzVy+ncfd9LH7FhbeEmeK2SB4yV3SNcQidIumpHasLnZF4mOh9Hhwfv/b1dYz2xV9l8AgLI0fyDBAjE2Yb8Y6YSE4AH437pFuUm3fzP7xz95E+xTbKPt4lwTb3mSSCWflf4ia0LobHifptR7qNQG+yXYxzE+iHRLDs8NIqB9Be8SD22HB8p2HZ6PyaRtMtU45na9gR+INHtBeufXMfLDKMnu/54ISyzvDTs4MeT4EzIJIiLrfqcag1y8bUrPj/nIyl/82tX98FRfrQWzjYWvMM++jRWK6reNrENv24iJyxS0e46h7XSeOiwhznzlvXInXkMky2aRJ0lTnq9H3ESgRoEDq3w1vEcwuO9er584B5Isozis/WksfSxhdW3YAEOarwTtY+K2/ZL+5lHgpNX99+RyY7XqhWTDWuu/qjahJuwHJttoJrDtWKeqfxgKpauScDtjDxX1fhd3coUArMS86d4Cgo7WUxYJs59EwRe8Rhee0NqVA6s1dWQD7dWj8s8jeDT46yvZgYW+jRWIr6VI3pV0JXrSr/AIYIEXKNTeGu4pdkmRxvDHCQxH/Y3dqMmbIgm3MbLSkBeks=
  matrix:
  - GIT_BACKUP_DIR=/tmp/backup
script:
- base=$(echo $PWD | sed "s|$GOPATH/src/||") && go test -race -v $(go list ./... |
  grep -v vendor | sed "s|$base/|./|")
- "$GOPATH/bin/goveralls -service=travis-ci"
